### ISSUE TITLE
Inbox not display content !

### ISSUE THREAD

**Issue by ndkimhao** [andela-tsolarin/disgui.se#1]
I've found a bug on the file received.client.view.html, on the last line, it should be

``` html
   <div class="message-content container-fluid" ng-bind-html="message.html || message.text"></div>
```

not

``` html
   <div class="message-content container-fluid" ng-bind-html="message.html"></div>
```

I am very interesting with your project, can I contribute to your repository? I also have idea to use the project on the free hosting such as Heroku, no need delicated server or VPS, so it can be more widely using because not every one have VPS :))

Sorry for my English grammar mistake :D

**Comment by tonerdo** [comment]
Sorry for not responding sooner I've been really busy at work, you're very much welcome to contribute to this repo. On the issue of deployment it currently runs in a dedicated virtual machine on Microsoft Azure (http://disgui.se), I initially tried hosting it on heroku but I was unable to run my mail server as there are limits to how an app specifies ports. So for now this app can only be run on a dedicated server.

**Comment by ndkimhao** [comment]
This is why i am trying to implement mandrill api, so it can run on service like heroku or openshift.
