### ISSUE TITLE
disgui.se seem down!

### ISSUE THREAD

**Issue by ndkimhao** [andela-tsolarin/disgui.se#5]
![image](https://cloud.githubusercontent.com/assets/7188260/13570964/37399188-e4a4-11e5-9c86-f6a725c5e6d8.png)
![image](https://cloud.githubusercontent.com/assets/7188260/13570999/764d7060-e4a4-11e5-8039-47f533491f28.png)

Hi! I'm sorry for long time inactive, I have so many exams in school that I cannot breath :D, your server seem down from my location.
I suggest using some free but reliable service, because we don't have to handle very much traffic. I use openshift for my clone hmail.ml for many months, it just work and I don't have to touch it for a long time :D I think one of the most important factors of email service is reliability, because users don't want to lost their mails !

**Comment by tonerdo** [comment]
@ndkimhao sorry for the late response as well, been really busy at work. It weird that it keeps going down, but I doubt I have a fault proof deployment setup. I'll look into it. In the meantime will you be willing to co-own disguise with me. Instead of having clones we can actually work to have this code up and running very well on http://disgui.se. Maybe even put it on product hunt. You interested?

**Comment by ndkimhao** [comment]
Of course :D I just create this site for private use (some site don't allow public anonymous mail service); I use the old version code because i was too lazy to update :)) But my site keep running 24/7 like a charm :))
can i have access to your server to investigate the problem?

**Comment by tonerdo** [comment]
@ndkimhao I was thinking more along the lines of setting up a new server together entirely from scratch. I have an MSDN subscription which means I can access all the goodies Microsoft Azure, relatively free. Hosting is taking care of. I'm thinking of leveraging your mandrill addition so i don't have to set up the entire infrastructure in a VM like I currently do

**Comment by ndkimhao** [comment]
yeah, i totally agree with you :D i have use mandrill for many months for free without maintenance.
Moreover, i think we should setup some accounts in Sendgrid in order to send mail. All mail from custom mail server go to Spam folder

**Comment by ndkimhao** [comment]
Also, if you have root access to server, i think we should use nginx as static file-server, so it will free works for node. Cloudflare also help speed up website across the world

**Comment by tonerdo** [comment]
Any ideas how much all this will cost?

**Comment by ndkimhao** [comment]
If you want, we can make it all free :)) Cloudflare, nginx, mandrill are all free. But Sendgrid only allow to send 12k mail/month for free. So if we need to send more mails, we can make some "fake" sending domain and accounts, and set "reply-to" field to our main domain

**Comment by tonerdo** [comment]
@ndkimhao give me a few days to think how best we can share the work among us. I'm open to any suggestions you might have of course!!!
